---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app-test
  namespace: web-store
spec:
  chart:
    spec:
      chart: chartmuseum/app
      sourceRef:
        kind: HelmRepository
        name: chartmuseum
        namespace: flux-system
      version: 0.1.0
      interval: 1m0s
  values:
    replicaCount: 2
