---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: web-app
  namespace: web-store
spec:
  chart:
    spec:
      chart: app
      sourceRef:
        kind: HelmRepository
        name: chartmuseum
        namespace: flux-system
      version: 0.1.0
  interval: 1m0s
